language: node_js
node_js:
  - "10"
# dist: xenial
sudo: required
branches:
  only:
  - master
before_script:
  - echo "before script here"
script:
- npm ci
- npm run build
# - npm run test-all-headless
# - npm run e2e-headless